### ISSUE TITLE
crashes on start in 1.19.3 fabric

### ISSUE THREAD

**Issue by EGOIST1372** [Darkhax-Minecraft/Dark-Paintings#13]
crashes on start in 1.19.3 fabric
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'darkpaintings'!

**Comment by Darkhax** [comment]
Hello, please include the full crash log.

**Comment by EGOIST1372** [comment]
this is without not enough crashes mod
its with mixin trace mod

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-01-12 03:31:04
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'darkpaintings'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: REGISTRIES
	at net.darkhax.darkpaintings.DarkPaintingsContent.init(DarkPaintingsContent.java:12)
	at net.darkhax.darkpaintings.DarkPaintingsFabric.onInitialize(DarkPaintingsFabric.java:10)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
Mixins in Stacktrace:
	net.minecraft.class_310:
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.MinecraftClient_screenshotMixin (memoryleakfix.mixins.json)
		dev.notalpha.dashloader.mixin.main.MinecraftClientMixin (dashloader.mixins.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (freecam.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		de.maxhenkel.camerautils.mixin.MinecraftMixin (camerautils.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
		ca.fxco.memoryleakfix.mixin.customPayloadLeak.MinecraftClient_freeBufferMixin (memoryleakfix.mixins.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (sodium.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.client.MixinMinecraftClient (drippyloadingscreen.mixin.json)
		de.maxhenkel.status.mixin.MinecraftMixin (status.mixins.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.MinecraftClient_targetClearMixin (memoryleakfix.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)

**Comment by EGOIST1372** [comment]
also when I installed not enough crashes mod I got these errors as well
// I bet Cylons wouldn't have this problem.

Time: 2023-01-12 03:21:01
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "com.replaymod.core.ReplayMod.getSettingsRegistry()" because "com.replaymod.core.ReplayMod.instance" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.client.gui.screen.TitleScreen.modify$ddi000$adjustRealmsButton(TitleScreen:2522)
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen:146)
	at net.minecraft.client.gui.screen.Screen.method_41843(Screen:392)
	at net.minecraft.client.gui.screen.Screen.init(Screen:383)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1049)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:673)
	at net.minecraft.client.main.Main.method_44604(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_442.modify$ddi000$adjustRealmsButton(class_442.java:2522)
	at net.minecraft.class_442.method_25426(class_442.java:146)
	at net.minecraft.class_437.method_41843(class_437.java:392)
	at net.minecraft.class_437.method_25423(class_437.java:383)
	at net.minecraft.class_310.method_1507(class_310.java:1049)
	at net.minecraft.class_310.<init>(class_310.java:673)
	
	and after I removed replymod this crash report I got from not enough crashes mod
	// Shall we play a game?

Time: 2023-01-12 03:25:06
Description: Initializing game

java.lang.IllegalStateException: Config not yet available
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:38)
	at net.minecraft.client.MinecraftClient.handler$cmn000$postInit(MinecraftClient:19978)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:675)
	at net.minecraft.client.main.Main.method_44604(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.SodiumClientMod.options(SodiumClientMod.java:38)
	at net.minecraft.class_310.handler$cmn000$postInit(class_310.java:19978)
	at net.minecraft.class_310.<init>(class_310.java:675)

	but clearly they all gone when I removed Dark paintings and installed back replymod and sodium

**Comment by Darkhax** [comment]
Are you sure that you also have the Bookshelf mod installed? It is listed as a required dependency on the CurseForge file page.

**Comment by EGOIST1372** [comment]
Yes I have latest 1.19.3 bookshelf mod installed

**Comment by Darkhax** [comment]
Please include the full latest.log file.

**Comment by EGOIST1372** [comment]
latest.log 

[12:40:48] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[12:40:49] [main/INFO]: Loading 140 mods:
	- advancementinfo 1.19.3-fabric0.68.1-1.3.1
	- architectury 7.0.66
	- audioplayer 1.19.3-1.4.5
	- auudio 1.0.3
	- bettermounthud 1.2.1
	- biomeinfo 1.19.2-12
	- bookshelf 17.0.3
	- camerautils 1.19.3-1.0.3
	- cem 0.7.1
	- chalk 2.1.1
	- chalk-colorful-addon 2.1.1+1.19.3
	- chat_heads 0.9.0
	- chime 1.4.0
	- citresewn 1.1.3+1.19.3
	- citresewn-defaults 1.1.3+1.19.3 via citresewn
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 9.0.94
	- clumps 9.0.0+16
	- coat 1.0.0-beta.19+mc22w44a via completeconfig
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- completeconfig 2.2.0
	- completeconfig-base 2.2.0 via cem
	- completeconfig-gui-cloth 2.2.0 via cem
	- completeconfig-gui-yacl 2.2.0 via completeconfig
	- controlling 10.0+9
	- creativeonepunch 1.3
	- darkpaintings 13.1.4
	- dashloader 5.0.0-alpha.6+1.19.3
	- dev_quantumfusion_hyphen 0.4.0-rc.2 via dashloader
	- dev_quantumfusion_taski 2.1.0 via dashloader
	- drippyloadingscreen 1.6.6
	- dynamicfps 2.2.0
	- entity_texture_features 4.3.1
	- entityculling 1.5.2-mc1.19.3
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.72.0+1.19.3
	- fabric-api-base 0.4.20+afca2f3e85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.19+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.0+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.4+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.29+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.11+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.21+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.0+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.38+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.46+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.0+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.1+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.13+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.1.4+1134c5b885 via fabric-api
	- fabric-dimensions-v1 2.1.40+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.6+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.39+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.42+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.29+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.8+1134c5b885 via fabric-api
	- fabric-item-group-api-v1 2.1.11+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.30+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.28+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.9+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.19+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.23+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.13+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.30+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.26+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.16+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.33+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.3.0+85f102ee85 via fabric-api
	- fabric-particles-v1 1.0.19+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.0+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.4+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.0+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.0+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.29+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.24+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.17+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.32+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.0+6dc0edd785 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.2+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.4+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.40+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.12+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.7+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.14+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.0+5b9a588b85 via fabric-api
	- fabricloader 0.14.12
	- fallingleaves 1.14.3+1.19.3
	- fancymenu 2.13.2
	- fastopenlinksandfolders 1.1.1
	- ferritecore 5.1.0
	- fmextension_audio 1.1.1
	- freecam 1.1.8+1.19
	- indium 1.0.12+mc1.19.3
	- inventoryhud 3.4.7
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- iris 1.5.1
	- itemswapper 0.3.2-mc1.19.3
	- java 17
	- keepheadnames 1.5.1
	- konkrete 1.6.0
	- krypton 0.2.1
	- lazydfu 0.1.3
	- lightoverlay 7.0.2
	- lithium 0.10.4
	- loadmyresources 1.0.4
	- malilib 0.14.0
	- memoryleakfix 1.19.3-0.7.0
	- microdurability 0.3.6+1.19
	- microdurability-core 0.3.6 via microdurability
	- midnightlib 1.1.0 via puzzle
	- minecraft 1.19.3
	- minihud 0.25.0
	- mixintrace 1.1.1+1.17
	- modmenu 5.0.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_apache_httpcomponents_httpmime 4.5.10 via entity_texture_features
	- phosphor 0.8.1
	- polymer-registry-sync-manipulator 0.3.0-rc.3+1.19.3 via vcinteraction
	- puzzle 1.4.2-1.19.3
	- puzzle-base 1.4.2-1.19.3 via puzzle
	- puzzle-gui 1.4.2-1.19.3 via puzzle
	- puzzle-models 1.4.2-1.19.3 via puzzle
	- puzzle-splashscreen 1.4.2-1.19.3 via puzzle
	- replaymod 1.19.3-2.6.10
	- replayvoicechat 1.19.3-1.2.4
	- roughlyenoughitems 10.0.581
	- searchlight 1.1.9
	- shulkerboxtooltip 3.2.4+1.19.3
	- skinlayers 1.5.2-mc1.19.3
	- smoothboot 1.19-1.7.1
	- sodium 0.4.8+build.22
	- sound_physics_remastered 1.19.3-1.0.18
	- status 1.19.3-1.0.0
	- vcinteraction 1.19.3-1.0.3
	- voicechat 1.19.3-2.3.26
	- wi_zoom 1.4-MC1.19.3
[12:40:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:40:50] [main/INFO]: Compatibility level set to JAVA_16
[12:40:50] [main/INFO]: Compatibility level set to JAVA_17
[12:40:51] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 2 override(s) found
[12:40:51] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[12:40:51] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 1 override(s) found
[12:40:53] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[12:40:53] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[12:40:53] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[12:40:53] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[12:40:53] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[12:40:53] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[12:40:55] [main/INFO]: Smooth Boot config initialized
[12:41:01] [main/WARN]: Discarding @Unique public method getAnimatedSkin in 3dskinlayers.mixins.json:DonorAbstractClientPlayerMixin from mod skinlayers because it already exists in net.minecraft.class_742
[12:41:04] [main/INFO]: Building unoptimized datafixer
[12:41:07] [main/INFO]: Minecraft bootstrap in 10.1s
[12:41:08] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[12:41:08] [Render thread/INFO]: Launching a new process to probe the system configuration!
[12:41:09] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[12:41:09] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 980M/PCIe/SSE2
[12:41:09] [Render thread/INFO]: OpenGL Version: 3.3.0 NVIDIA 497.29
[12:41:09] [Render thread/WARN]: Enabling workaround for NVIDIA graphics drivers on Windows (issue #1486)
[12:41:09] [Render thread/WARN]: One or more workarounds were enabled to prevent crashes or other issues on your system. You may need to update your graphics drivers.
[12:41:10] [Render thread/INFO]: [LOAD MY RESOURCES] PackHandler initialized!
[12:41:10] [Render thread/INFO]: [LOAD MY RESOURCES] Pack registered!
[12:41:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:41:11] [Render thread/INFO]: Setting user:
[12:41:12] [Render thread/INFO]: Initialized!
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tadpole_bucket is now minecraft:bucket.
[12:41:12] [Render thread/INFO]: [Chalk] Detecting Loader...
[12:41:12] [Render thread/INFO]: [Chalk] Detected Loader: Fabric
[12:41:12] [Render thread/INFO]: [Chalk] Registering blocks and items...
[12:41:12] [Render thread/INFO]: [Chalk] Startup finished!
[12:41:12] [Render thread/INFO]: [DRIPPY LOADING SCREEN] FancyMenu detected!
[12:41:13] [Render thread/INFO]: [FANCYMENU] Loading v2.13.2 in client-side mode!
[12:41:13] [Render thread/INFO]: [FANCYMENU] Level registry interactions allowed!
[12:41:13] [Render thread/INFO]: [KONKRETE] Successfully initialized!
[12:41:13] [Render thread/INFO]: [KONKRETE] Server-side libs ready to use!
[12:41:13] [Render thread/INFO]: Compression will use Java, encryption will use Java
[12:41:14] [Render thread/INFO]: [REI] Config loaded
[12:41:14] [Render thread/INFO]: Registering S2C receiver with id roughlyenoughitems:request_tags_s2c
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:request_tags_c2s
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientPlugin [roughlyenoughitems] for REIPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultClientRuntimePlugin [roughlyenoughitems] for REIPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[12:41:14] [Render thread/INFO]: [REI] Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:delete_item
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_grab
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:create_item_hotbar
[12:41:14] [Render thread/INFO]: Registering C2S receiver with id roughlyenoughitems:move_items
[12:41:14] [Render thread/INFO]: Reloading config
[12:41:14] [Render thread/INFO]: Reloading reverb parameters
[12:41:14] [Render thread/INFO]: Compatibility version 1
[12:41:14] [Render thread/INFO]: Compatibility version 15
[12:41:15] [Render thread/INFO]: Loading plugins
[12:41:15] [Render thread/INFO]: Loaded 4 plugin(s)
[12:41:15] [Render thread/INFO]: Initializing plugins
[12:41:15] [Render thread/INFO]: Initializing Simple Voice Chat integration
[12:41:15] [Render thread/INFO]: Initialized 4 plugin(s)
[12:41:15] [Render thread/INFO]: Registering events for audioplayer
[12:41:15] [Render thread/INFO]: Registering events for replayvoicechat
[12:41:15] [Render thread/INFO]: Registering events for sound_physics_remastered
[12:41:15] [Render thread/INFO]: Registering events for vcinteraction
[12:41:15] [Render thread/INFO]: [STDOUT]: Starting WI Zoom v1.4-MC1.19.3

**Comment by Darkhax** [comment]
It looks like you're using Dark Paintings13.1.4 which is for Minecraft 1.19.2 only. Version 14.0.1 is for 1.19.3 and should work fine. You generally can't use 1.19.2 mods on 1.19.3 so make sure you have the correct versions of your other mods as well.

**Comment by EGOIST1372** [comment]
I'm so so sorry
I swear I downloaded the 1.19.3 version but it seems yeah I downloaded the wrong version somehow (probably fat fingered xD )
Again I'm sorry to waste your time
